
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 27 17:04:10 CST 2018
//----------------------------------------------------

package Gramatica_DASM;

/** CUP generated class containing symbol constants. */
public class simbolo_DASM {
  /* terminals */
  public static final int numero_completo = 2;
  public static final int i_entero = 32;
  public static final int call = 30;
  public static final int palabra = 4;
  public static final int function = 27;
  public static final int add = 6;
  public static final int mod = 10;
  public static final int oval = 37;
  public static final int calc = 34;
  public static final int eqz = 15;
  public static final int gte = 14;
  public static final int gt = 12;
  public static final int line = 40;
  public static final int i_flotante = 33;
  public static final int set_global = 24;
  public static final int tee_global = 26;
  public static final int end = 28;
  public static final int tee_local = 25;
  public static final int quadrate = 36;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int diff = 7;
  public static final int lt = 11;
  public static final int or = 17;
  public static final int lte = 13;
  public static final int i_caracter = 31;
  public static final int point = 39;
  public static final int br_if = 20;
  public static final int mult = 8;
  public static final int get_global = 22;
  public static final int texto = 38;
  public static final int and = 16;
  public static final int br = 19;
  public static final int not = 18;
  public static final int dolar = 3;
  public static final int get_local = 21;
  public static final int print = 29;
  public static final int div = 9;
  public static final int principal = 5;
  public static final int retorno = 35;
  public static final int set_local = 23;
}

